# Generated by Django 4.2.28 on 2026-04-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_category_coursesection_lesson_course_is_published_and_more"),
        ("pdfs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfmaterial",
            name="course",
        ),
        migrations.AddField(
            model_name="pdfmaterial",
            name="lesson",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdfs",
                to="courses.lesson",
            ),
        ),
    ]
